apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: dev
spec:
  containers:
    - name: hello
      image: hilel14/hello-dotnet
  restartPolicy: Never
